name: ci-cd

on: [push, pull_request]

jobs:
  ci:
    # setup operating system
    runs-on: ubuntu-latest

    # define job steps
    steps:
    - name: setup python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: check-out repository
      uses: actions/checkout@v2

    - name: install poetry
      uses: snok/install-poetry@v1

    - name: install packages
      run: poetry install

    - name: test with pytest
      run: poetry run pytest tests/ --cov=pycounts_gaurav --cov-report=xml
    
    - name: use codecov to track coverage
      uses: codecov/codecov-action@v2
      with:
        files: ./coverage.xml # coverage report

    - name: build documentation
      run: poetry run make html --directory docs/

    

